### PR TITLE
Hosted this app

### PR DESCRIPTION
**Pull request by vikram2009**
hosted this app on - https://html-and-css-etlg.vercel.app/

### CODE REVIEW

**Comment by AkshayAnand2002** [comment]
> hosted this app on - https://html-and-css-etlg.vercel.app/

Pls. stop hosting this calculator program. 
I made the project for learning and not for hosting.
I request you stop hosting.

**Comment by AkshayAnand2002** [comment]
> > hosted this app on - https://html-and-css-etlg.vercel.app/
> 
> Pls. stop hosting this calculator program. I made the project for learning and not for hosting. I request you stop hosting.

YOU SHOULD NOT HAVE HOSTED THIS WITHOUT MY PERMISSION. 
ALSO IF ANY CHARGES ARE TO BE PAID, I WILL NOT BE RESPONSIBLE FOR THAT.
 IF YOU CONTINUE HOSTING PLS. GIVE CREDIT TO ME ALSO .

**Comment by vikram2009** [comment]
just a sec lemme remove it

**Comment by vikram2009** [comment]
and its freeee

**Comment by vikram2009** [comment]
# done

**Comment by AkshayAnand2002** [comment]
> and its freeee

IT IS FREE FOR ALL TIME OR FOR LIMITED TIME ? PLS. TELL

**Comment by vikram2009** [comment]
its freee until
u have the repo live

**Comment by vikram2009** [comment]
use github pages its freee

**Comment by AkshayAnand2002** [comment]
> use github pages its freee

OK THANKS!!

**Pull request closed without merging**
